name: Build and deploy to GitHub Pages
â€‹
on:
  push:
    branches: [main]
â€‹
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
â€‹
      - name: Install ğŸ”§
        run: |
          npm ci
â€‹
      - name: 'Create env file'
        run: |
          touch .env
          echo keyMaks = ${{ secrets.keyMaks }} >> .env
          echo keyDenys = ${{ secrets.keyDenys}} >> .env
          echo fireBaseConfig = ${{ secrets.fireBaseConfig }} >> .env
          cat .env
â€‹
      - name: Build ğŸ”§
        run: |
          npm run build
â€‹
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
